/*
@license
dhtmlxScheduler v.4.4.9 Professional

This software is covered by DHTMLX Commercial License. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
scheduler.config.multisection=!0,scheduler.config.multisection_shift_all=!0,scheduler.config.section_delimiter=",",scheduler.attachEvent("onSchedulerReady",function(){scheduler._inited_multisection_copies||(scheduler.attachEvent("onEventIdChange",function(e,t){var a=this._multisection_copies;if(a&&a[e]&&!a[t]){var r=a[e];delete a[e],a[t]=r}}),scheduler._inited_multisection_copies=!0),scheduler._register_copies_array=function(e){for(var t=0;t<e.length;t++)this._register_copy(e[t])},scheduler._register_copy=function(e){
this._multisection_copies[e.id]||(this._multisection_copies[e.id]={});var t=e[this._get_section_property()],a=this._multisection_copies[e.id];a[t]||(a[t]=e)},scheduler._get_copied_event=function(e,t){if(!this._multisection_copies[e])return null;if(this._multisection_copies[e][t])return this._multisection_copies[e][t];var a=this._multisection_copies[e];if(scheduler._drag_event&&scheduler._drag_event._orig_section&&a[scheduler._drag_event._orig_section])return a[scheduler._drag_event._orig_section];
var r=1/0,i=null;for(var n in a)a[n]._sorder<r&&(i=a[n],r=a[n]._sorder);return i},scheduler._clear_copied_events=function(){this._multisection_copies={}},scheduler._restore_render_flags=function(e){for(var t=this._get_section_property(),a=0;a<e.length;a++){var r=e[a],i=scheduler._get_copied_event(r.id,r[t]);if(i)for(var n in i)0===n.indexOf("_")&&(r[n]=i[n])}};var e=scheduler._update_unit_section;scheduler._update_unit_section=function(t){return scheduler._update_sections(t,e)};var t=scheduler._update_timeline_section;
scheduler._update_timeline_section=function(e){return scheduler._update_sections(e,t)},scheduler.isMultisectionEvent=function(e){if(e&&this._get_multisection_view()){var t=this._get_event_sections(e);return t.length>1}return!1},scheduler._get_event_sections=function(e){var t=this._get_section_property(),a=e[t]||"";return this._parse_event_sections(a)},scheduler._parse_event_sections=function(e){return e instanceof Array?e:e.toString().split(scheduler.config.section_delimiter)},scheduler._clear_copied_events(),
scheduler._split_events=function(e){var t=[],a=this._get_multisection_view(),r=this._get_section_property();if(a)for(var i=0;i<e.length;i++){var n=this._get_event_sections(e[i]);if(n.length>1){for(var s=0;s<n.length;s++)if("undefined"!=typeof a.order[n[s]]){var d=scheduler._copy_event(e[i]);d[r]=n[s],t.push(d)}}else t.push(e[i])}else t=e;return t},scheduler._get_multisection_view=function(){return this.config.multisection?scheduler._get_section_view():!1};var a=scheduler.get_visible_events;scheduler.get_visible_events=function(e){
this._clear_copied_events();var t=a.apply(this,arguments);if(this._get_multisection_view()){t=this._split_events(t);for(var r=0;r<t.length;r++)this.is_visible_events(t[r])||(t.splice(r,1),r--);this._register_copies_array(t)}return t},scheduler._rendered_events={};var r=scheduler.render_view_data;scheduler.render_view_data=function(e,t){return this._get_multisection_view()&&e&&(e=this._split_events(e),this._restore_render_flags(e)),r.apply(this,[e,t])},scheduler._update_sections=function(e,t){var a=e.view,r=e.event,i=e.pos;
if(scheduler.isMultisectionEvent(r)){if(scheduler._drag_event._orig_section||(scheduler._drag_event._orig_section=i.section),scheduler._drag_event._orig_section!=i.section){var n=a.order[i.section]-a.order[scheduler._drag_event._orig_section];if(n){var s=this._get_event_sections(r),d=[],l=!0;if(scheduler.config.multisection_shift_all)for(var o=0;o<s.length;o++){var _=scheduler._shift_sections(a,s[o],n);if(null===_){d=s,l=!1;break}d[o]=_}else for(var o=0;o<s.length;o++){if(s[o]==i.section){d=s,l=!1;
break}if(s[o]==scheduler._drag_event._orig_section){var _=scheduler._shift_sections(a,s[o],n);if(null===_){d=s,l=!1;break}d[o]=_}else d[o]=s[o]}l&&(scheduler._drag_event._orig_section=i.section),r[scheduler._get_section_property()]=d.join(scheduler.config.section_delimiter)}}}else t.apply(scheduler,[e])},scheduler._shift_sections=function(e,t,a){for(var r=null,i=e.y_unit||e.options,n=0;n<i.length;n++)if(i[n].key==t){r=n;break}var s=i[r+a];return s?s.key:null};var i=scheduler._get_blocked_zones;scheduler._get_blocked_zones=function(e,t,a,r,n){
if(t&&this.config.multisection){t=this._parse_event_sections(t);for(var s=[],d=0;d<t.length;d++)s=s.concat(i.apply(this,[e,t[d],a,r,n]));return s}return i.apply(this,arguments)};var n=scheduler._check_sections_collision;scheduler._check_sections_collision=function(e,t){if(this.config.multisection&&this._get_section_view()){e=this._split_events([e]),t=this._split_events([t]);for(var a=!1,r=0,i=e.length;i>r&&!a;r++)for(var s=0,d=t.length;d>s;s++)if(n.apply(this,[e[r],t[s]])){a=!0;break}return a}return n.apply(this,arguments);
}});
//# sourceMappingURL=../sources/ext/dhtmlxscheduler_multisection.js.map