/*
@license
dhtmlxScheduler v.4.4.9 Professional

This software is covered by DHTMLX Commercial License. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
scheduler._props={},scheduler.createUnitsView=function(e,t,r,a,i,n,s){"object"==typeof e&&(r=e.list,t=e.property,a=e.size||0,i=e.step||1,n=e.skip_incorrect,s=e.days||1,e=e.name),scheduler._props[e]={map_to:t,options:r,step:i,position:0,days:s},a>scheduler._props[e].options.length&&(scheduler._props[e]._original_size=a,a=0),scheduler._props[e].size=a,scheduler._props[e].skip_incorrect=n||!1,scheduler.date[e+"_start"]=scheduler.date.day_start,scheduler.templates[e+"_date"]=function(t,r){var a=scheduler._props[e];
return a.days>1?scheduler.templates.week_date(t,r):scheduler.templates.day_date(t)},scheduler._get_unit_index=function(e,t){var r=e.position||0,a=Math.round((scheduler._correct_shift(+t,1)-+scheduler._min_date)/864e5),i=e.options.length;return a>=i&&(a%=i),r+a},scheduler.templates[e+"_scale_text"]=function(e,t,r){return r.css?"<span class='"+r.css+"'>"+t+"</span>":t},scheduler.templates[e+"_scale_date"]=function(t){var r=scheduler._props[e],a=r.options;if(!a.length)return"";var i=scheduler._get_unit_index(r,t),n=a[i];
return scheduler.templates[e+"_scale_text"](n.key,n.label,n)},scheduler.templates[e+"_second_scale_date"]=function(e){return scheduler.templates.week_scale_date(e)},scheduler.date["add_"+e]=function(t,r){return scheduler.date.add(t,r*scheduler._props[e].days,"day")},scheduler.date["get_"+e+"_end"]=function(t){return scheduler.date.add(t,(scheduler._props[e].size||scheduler._props[e].options.length)*scheduler._props[e].days,"day")},scheduler.attachEvent("onOptionsLoad",function(){for(var t=scheduler._props[e],r=t.order={},a=t.options,i=0;i<a.length;i++)r[a[i].key]=i;
t._original_size&&0===t.size&&(t.size=t._original_size,delete t.original_size),t.size>a.length?(t._original_size=t.size,t.size=0):t.size=t._original_size||t.size,scheduler._date&&scheduler._mode==e&&scheduler.setCurrentView(scheduler._date,scheduler._mode)}),scheduler["mouse_"+e]=function(e){var t=scheduler._props[this._mode];if(t){if(e=this._week_indexes_from_pos(e),this._drag_event||(this._drag_event={}),this._drag_id&&this._drag_mode&&(this._drag_event._dhx_changed=!0),this._drag_mode&&"new-size"==this._drag_mode){
var r=scheduler._get_event_sday(scheduler._events[scheduler._drag_id]);Math.floor(e.x/t.options.length)!=Math.floor(r/t.options.length)&&(e.x=r)}var a=e.x%t.options.length,i=Math.min(a+t.position,t.options.length-1);e.section=(t.options[i]||{}).key,e.x=Math.floor(e.x/t.options.length);var n=this.getEvent(this._drag_id);this._update_unit_section({view:t,event:n,pos:e})}return e.force_redraw=!0,e},scheduler.callEvent("onOptionsLoad",[])},scheduler._update_unit_section=function(e){var t=e.view,r=e.event,a=e.pos;
r&&(r[t.map_to]=a.section)},scheduler.scrollUnit=function(e){var t=scheduler._props[this._mode];t&&(t.position=Math.min(Math.max(0,t.position+e),t.options.length-t.size),this.setCurrentView())},function(){var e=function(e){var t=scheduler._props[scheduler._mode];if(t&&t.order&&t.skip_incorrect){for(var r=[],a=0;a<e.length;a++)"undefined"!=typeof t.order[e[a][t.map_to]]&&r.push(e[a]);e.splice(0,e.length),e.push.apply(e,r)}return e},t=scheduler._pre_render_events_table;scheduler._pre_render_events_table=function(r,a){
return r=e(r),t.apply(this,[r,a])};var r=scheduler._pre_render_events_line;scheduler._pre_render_events_line=function(t,a){return t=e(t),r.apply(this,[t,a])};var a=function(e,t){if(e&&"undefined"==typeof e.order[t[e.map_to]]){var r=scheduler,a=864e5,i=Math.floor((t.end_date-r._min_date)/a);return e.options.length&&(t[e.map_to]=e.options[Math.min(i+e.position,e.options.length-1)].key),!0}},i=scheduler.is_visible_events;scheduler.is_visible_events=function(e){var t=i.apply(this,arguments);if(t){var r=scheduler._props[this._mode];
if(r&&r.size){var a=r.order[e[r.map_to]];if(a<r.position||a>=r.size+r.position)return!1}}return t};var n=scheduler._process_ignores;scheduler._process_ignores=function(e,t,r,a,i){if(!scheduler._props[this._mode])return void n.call(this,e,t,r,a,i);this._ignores={},this._ignores_detected=0;var s=scheduler["ignore_"+this._mode];if(s){var d=scheduler._props&&scheduler._props[this._mode]?scheduler._props[this._mode].size||scheduler._props[this._mode].options.length:1;t/=d;for(var l=new Date(e),o=0;t>o;o++){
if(s(l))for(var _=o*d,c=(o+1)*d,h=_;c>h;h++)this._ignores_detected+=1,this._ignores[h]=!0,i&&t++;l=scheduler.date.add(l,a,r),scheduler.date[r+"_start"]&&(l=scheduler.date[r+"_start"](l))}}};var s=scheduler._reset_scale;scheduler._reset_scale=function(){var e=scheduler._props[this._mode],t=s.apply(this,arguments);if(e){this._max_date=this.date.add(this._min_date,e.days,"day");for(var r=this._els.dhx_cal_data[0].childNodes,a=0;a<r.length;a++)r[a].className=r[a].className.replace("_now","");var i=this._currentDate();
if(i.valueOf()>=this._min_date&&i.valueOf()<this._max_date){var n=864e5,d=Math.floor((i-scheduler._min_date)/n),l=e.options.length,o=d*l,_=o+l;for(a=o;_>a;a++)r[a]&&(r[a].className=r[a].className.replace("dhx_scale_holder","dhx_scale_holder_now"))}if(e.size&&e.size<e.options.length){var c=this._els.dhx_cal_header[0],h=document.createElement("DIV");e.position&&(this._waiAria.headerButtonsAttributes(h,""),h.className="dhx_cal_prev_button",h.style.cssText="left:1px;top:2px;position:absolute;",h.innerHTML="&nbsp;",
c.firstChild.appendChild(h),h.onclick=function(){scheduler.scrollUnit(-1*e.step)}),e.position+e.size<e.options.length&&(this._waiAria.headerButtonsAttributes(h,""),h=document.createElement("DIV"),h.className="dhx_cal_next_button",h.style.cssText="left:auto; right:0px;top:2px;position:absolute;",h.innerHTML="&nbsp;",c.lastChild.appendChild(h),h.onclick=function(){scheduler.scrollUnit(e.step)})}}return t};var d=scheduler._reset_scale;scheduler._reset_scale=function(){var e=scheduler._props[this._mode],t=scheduler.xy.scale_height;
e&&e.days>1?this._header_resized||(this._header_resized=scheduler.xy.scale_height,scheduler.xy.scale_height=2*t):this._header_resized&&(scheduler.xy.scale_height/=2,this._header_resized=!1),d.apply(this,arguments)};var l=scheduler._get_view_end;scheduler._get_view_end=function(){var e=scheduler._props[this._mode];if(e&&e.days>1){var t=this._get_timeunit_start();return scheduler.date.add(t,e.days,"day")}return l.apply(this,arguments)};var o=scheduler._render_x_header;scheduler._render_x_header=function(e,t,r,a){
var i=scheduler._props[this._mode];if(!i||i.days<=1)return o.apply(this,arguments);if(i.days>1){var n=scheduler.xy.scale_height;scheduler.xy.scale_height=Math.ceil(n/2),o.call(this,e,t,r,a,Math.ceil(scheduler.xy.scale_height));var s=i.options.length;if((e+1)%s===0){var d=document.createElement("DIV");d.className="dhx_scale_bar dhx_second_scale_bar";var l=this.date.add(this._min_date,Math.floor(e/s),"day");this.templates[this._mode+"_second_scalex_class"]&&(d.className+=" "+this.templates[this._mode+"_second_scalex_class"](new Date(l)));
var _,c=this._cols[e]*s-1;_=s>1?this._colsS[e-(s-1)]-this.xy.scale_width-2:t,this.set_xy(d,c,this.xy.scale_height-2,_,0),d.innerHTML=this.templates[this._mode+"_second_scale_date"](new Date(l),this._mode),a.appendChild(d)}scheduler.xy.scale_height=n}};var _=scheduler._get_event_sday;scheduler._get_event_sday=function(e){var t=scheduler._props[this._mode];if(t){if(t.days<=1)return a(t,e),this._get_section_sday(e[t.map_to]);var r=864e5,i=Math.floor((e.end_date.valueOf()-1-60*e.end_date.getTimezoneOffset()*1e3-(scheduler._min_date.valueOf()-60*scheduler._min_date.getTimezoneOffset()*1e3))/r),n=t.options.length,s=t.order[e[t.map_to]];
return i*n+s-t.position}return _.call(this,e)},scheduler._get_section_sday=function(e){var t=scheduler._props[this._mode];return t.order[e]-t.position};var c=scheduler.locate_holder_day;scheduler.locate_holder_day=function(e,t,r){var i=scheduler._props[this._mode];if(!i)return c.apply(this,arguments);var n;if(r?a(i,r):(r={start_date:e,end_date:e},n=0),i.days<=1)return 1*(void 0===n?i.order[r[i.map_to]]:n)+(t?1:0)-i.position;var s=864e5,d=Math.floor((r.start_date.valueOf()-scheduler._min_date.valueOf())/s),l=i.options.length,o=void 0===n?i.order[r[i.map_to]]:n;
return d*l+1*o+(t?1:0)-i.position};var h=scheduler._time_order;scheduler._time_order=function(e){var t=scheduler._props[this._mode];t?e.sort(function(e,r){return t.order[e[t.map_to]]>t.order[r[t.map_to]]?1:-1}):h.apply(this,arguments)};var u=scheduler._pre_render_events_table;scheduler._pre_render_events_table=function(e,t){function r(e){var t=scheduler.date.add(e,1,"day");return t=scheduler.date.date_part(t)}var a=scheduler._props[this._mode];if(a&&a.days>1&&!this.config.all_timed){for(var i={},n=0;n<e.length;n++){
var s=e[n];if(this.isOneDayEvent(e[n])){var d=+scheduler.date.date_part(new Date(s.start_date));i[d]||(i[d]=[]),i[d].push(s)}else{var l=new Date(Math.min(+s.end_date,+this._max_date)),o=new Date(Math.max(+s.start_date,+this._min_date));for(e.splice(n,1);+l>+o;){var _=this._copy_event(s);_.start_date=o,_.end_date=r(_.start_date),o=scheduler.date.add(o,1,"day");var d=+scheduler.date.date_part(new Date(o));i[d]||(i[d]=[]),i[d].push(_),e.splice(n,0,_),n++}n--}}var c=[];for(var n in i)c.splice.apply(c,[c.length-1,0].concat(u.apply(this,[i[n],t])));
for(var n=0;n<c.length;n++)this._ignores[c[n]._sday]?(c.splice(n,1),n--):c[n]._first_chunk=c[n]._last_chunk=!1;c.sort(function(e,t){return e.start_date.valueOf()==t.start_date.valueOf()?e.id>t.id?1:-1:e.start_date>t.start_date?1:-1}),e=c}else e=u.apply(this,[e,t]);return e},scheduler.attachEvent("onEventAdded",function(e,t){if(this._loading)return!0;for(var r in scheduler._props){var a=scheduler._props[r];"undefined"==typeof t[a.map_to]&&(t[a.map_to]=a.options[0].key)}return!0}),scheduler.attachEvent("onEventCreated",function(e,t){
var r=scheduler._props[this._mode];if(r&&t){var i=this.getEvent(e);a(r,i);var n=this._mouse_coords(t);this._update_unit_section({view:r,event:i,pos:n}),this.event_updated(i)}return!0})}();
//# sourceMappingURL=../sources/ext/dhtmlxscheduler_units.js.map