/*
@license
dhtmlxScheduler v.4.4.9 Professional

This software is covered by DHTMLX Commercial License. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
!function(){scheduler._grid={sort_rules:{"int":function(e,t,r){return 1*r(e)<1*r(t)?1:-1},str:function(e,t,r){return r(e)<r(t)?1:-1},date:function(e,t,r){return new Date(r(e))<new Date(r(t))?1:-1}},_getObjName:function(e){return"grid_"+e},_getViewName:function(e){return e.replace(/^grid_/,"")}}}(),scheduler.createGridView=function(e){function t(e){return!(void 0!==e&&(1*e!=e||0>e))}var r=e.name||"grid",i=scheduler._grid._getObjName(r);scheduler.config[r+"_start"]=e.from||new Date(0),scheduler.config[r+"_end"]=e.to||new Date(9999,1,1),
scheduler[i]=e,scheduler[i].defPadding=8,scheduler[i].columns=scheduler[i].fields,scheduler[i].unit=e.unit||"month",scheduler[i].step=e.step||1,delete scheduler[i].fields;for(var a=scheduler[i].columns,s=0;s<a.length;s++)t(a[s].width)&&(a[s].initialWidth=a[s].width),t(a[s].paddingLeft)||delete a[s].paddingLeft,t(a[s].paddingRight)||delete a[s].paddingRight;scheduler[i].select=void 0===e.select?!0:e.select,void 0===scheduler.locale.labels[r+"_tab"]&&(scheduler.locale.labels[r+"_tab"]=scheduler[i].label||scheduler.locale.labels.grid_tab),
scheduler[i]._selected_divs=[],scheduler.date[r+"_start"]=function(t){return scheduler.date[e.unit+"_start"]?scheduler.date[e.unit+"_start"](t):t},scheduler.date["add_"+r]=function(e,t){return scheduler.date.add(e,t*scheduler[i].step,scheduler[i].unit)},scheduler.templates[r+"_date"]=function(e,t){return scheduler.templates.day_date(e)+" - "+scheduler.templates.day_date(t)},scheduler.templates[r+"_full_date"]=function(e,t,i){return scheduler.isOneDayEvent(i)?this[r+"_single_date"](e):scheduler.templates.day_date(e)+" &ndash; "+scheduler.templates.day_date(t);
},scheduler.templates[r+"_single_date"]=function(e){return scheduler.templates.day_date(e)+" "+this.event_date(e)},scheduler.templates[r+"_field"]=function(e,t){return t[e]},scheduler.attachEvent("onTemplatesReady",function(){scheduler.attachEvent("onDblClick",function(e,t){return this._mode==r?(scheduler._click.buttons.details(e),!1):!0}),scheduler.attachEvent("onClick",function(e,t){return this._mode==r&&scheduler[i].select?(scheduler._grid.unselectEvent("",r),scheduler._grid.selectEvent(e,r,t),
!1):!0});var e=scheduler.render_data;scheduler.render_data=function(t){return this._mode!=r?e.apply(this,arguments):void scheduler._grid._fill_grid_tab(i)};var t=scheduler.render_view_data;scheduler.render_view_data=function(){var e=scheduler._els.dhx_cal_data[0].lastChild;return this._mode==r&&e&&(scheduler._grid._gridScrollTop=e.scrollTop),t.apply(this,arguments)}}),scheduler[r+"_view"]=function(e){if(scheduler._grid._sort_marker=null,delete scheduler._gridView,scheduler._grid._gridScrollTop=0,
scheduler._rendered=[],scheduler[i]._selected_divs=[],e){var t=null,a=null,s=scheduler[i];s.paging?(t=scheduler.date[r+"_start"](new Date(scheduler._date)),a=scheduler.date["add_"+r](t,1)):(t=scheduler.config[r+"_start"],a=scheduler.config[r+"_end"]),scheduler._min_date=t,scheduler._max_date=a,scheduler._grid.set_full_view(i);var n="";+t>+new Date(0)&&+a<+new Date(9999,1,1)&&(n=scheduler.templates[r+"_date"](t,a)),scheduler._els.dhx_cal_date[0].innerHTML=n,scheduler._gridView=i}}},scheduler.dblclick_dhx_grid_area=function(){
!this.config.readonly&&this.config.dblclick_create&&this.addEventNow()},scheduler._click.dhx_cal_header&&(scheduler._old_header_click=scheduler._click.dhx_cal_header),scheduler._click.dhx_cal_header=function(e){if(scheduler._gridView){var t=e||window.event,r=scheduler._grid._get_target_column(t,scheduler._gridView);scheduler._grid._toggle_sort_state(scheduler._gridView,r.id),scheduler.clear_view(),scheduler._grid._fill_grid_tab(scheduler._gridView)}else if(scheduler._old_header_click)return scheduler._old_header_click.apply(this,arguments);
},scheduler._grid.selectEvent=function(e,t,r){if(scheduler.callEvent("onBeforeRowSelect",[e,r])){var i=scheduler._grid._getObjName(t);scheduler.for_rendered(e,function(e){e.className+=" dhx_grid_event_selected",scheduler[i]._selected_divs.push(e)}),scheduler._select_id=e}},scheduler._grid._unselectDiv=function(e){e.className=e.className.replace(/ dhx_grid_event_selected/,"")},scheduler._grid.unselectEvent=function(e,t){var r=scheduler._grid._getObjName(t);if(r&&scheduler[r]._selected_divs)if(e){for(var i=0;i<scheduler[r]._selected_divs.length;i++)if(scheduler[r]._selected_divs[i].getAttribute("event_id")==e){
scheduler._grid._unselectDiv(scheduler[r]._selected_divs[i]),scheduler[r]._selected_divs.slice(i,1);break}}else{for(var i=0;i<scheduler[r]._selected_divs.length;i++)scheduler._grid._unselectDiv(scheduler[r]._selected_divs[i]);scheduler[r]._selected_divs=[]}},scheduler._grid._get_target_column=function(e,t){var r=e.originalTarget||e.srcElement,i=scheduler._getClassName(r);"dhx_grid_view_sort"==i&&(r=r.parentNode);for(var a=0,s=0;s<r.parentNode.childNodes.length;s++)if(r.parentNode.childNodes[s]==r){
a=s;break}return scheduler[t].columns[a]},scheduler._grid._get_sort_state=function(e){var t=scheduler[e];return t.sort},scheduler._grid._toggle_sort_state=function(e,t){var r=this._get_sort_state(e),i=scheduler[e];r&&r.column==t?r.direction="asc"==r.direction?"desc":"asc":i.sort={column:t,direction:"desc"}},scheduler._grid._get_sort_value_for_column=function(e){var t=null;if(e.template){var r=e.template;t=function(e){return r(e.start_date,e.end_date,e)}}else{var i=e.id;"date"==i&&(i="start_date"),
t=function(e){return e[i]}}return t},scheduler._grid.draw_sort_marker=function(e,t){if(scheduler._grid._sort_marker&&(scheduler._grid._sort_marker.className=scheduler._grid._sort_marker.className.replace(/( )?dhx_grid_sort_(asc|desc)/,""),scheduler._grid._sort_marker.removeChild(scheduler._grid._sort_marker.lastChild)),t){var r=scheduler._grid._get_column_node(e,t.column);r.className+=" dhx_grid_sort_"+t.direction,scheduler._grid._sort_marker=r;var i="<div class='dhx_grid_view_sort' style='left:"+(+r.style.width.replace("px","")-15+r.offsetLeft)+"px'>&nbsp;</div>";
r.innerHTML+=i}},scheduler._grid.sort_grid=function(e){e=e||{direction:"desc",value:function(e){return e.start_date},rule:scheduler._grid.sort_rules.date};var t=scheduler.get_visible_events();return t.sort(function(t,r){return e.rule(t,r,e.value)}),"asc"==e.direction&&(t=t.reverse()),t},scheduler._grid.set_full_view=function(e){if(e){var t=(scheduler.locale.labels,scheduler._grid._print_grid_header(e));scheduler._els.dhx_cal_header[0].innerHTML=t,scheduler._table_view=!0,scheduler.set_sizes()}},scheduler._grid._calcPadding=function(e,t){
return(void 0!==e.paddingLeft?1*e.paddingLeft:scheduler[t].defPadding)+(void 0!==e.paddingRight?1*e.paddingRight:scheduler[t].defPadding)},scheduler._grid._getStyles=function(e,t){for(var r=[],i="",a=0;t[a];a++)switch(i=t[a]+":",t[a]){case"text-align":e.align&&r.push(i+e.align);break;case"vertical-align":e.valign&&r.push(i+e.valign);break;case"padding-left":void 0!==e.paddingLeft&&r.push(i+(e.paddingLeft||"0")+"px");break;case"padding-right":void 0!==e.paddingRight&&r.push(i+(e.paddingRight||"0")+"px");
}return r},scheduler._grid._get_column_node=function(e,t){for(var r=-1,i=0;i<e.length;i++)if(e[i].id==t){r=i;break}return 0>r?null:scheduler._obj.querySelectorAll(".dhx_grid_line > div")[r]},scheduler._grid._get_sort_rule=function(e){var t,r=scheduler[e],i=this._get_sort_state(e);if(i){for(var a,s=0;s<r.columns.length;s++)if(r.columns[s].id==i.column){a=r.columns[s];break}if(a){var n=scheduler._grid._get_sort_value_for_column(a),d=a.sort;"function"!=typeof d&&(d=scheduler._grid.sort_rules[d]||scheduler._grid.sort_rules.str),
t={direction:i.direction,rule:d,value:n}}}return t},scheduler._grid._fill_grid_tab=function(e){var t=scheduler[e],r=this._get_sort_state(e),i=this._get_sort_rule(e);i&&scheduler._grid.draw_sort_marker(t.columns,r);for(var a=(scheduler._date,scheduler._grid.sort_grid(i)),s=scheduler[e].columns,n="<div>",d=-2,l=0;l<s.length;l++){var o=scheduler._grid._calcPadding(s[l],e);d+=s[l].width+o,l<s.length-1&&(n+="<div class='dhx_grid_v_border' style='left:"+d+"px'></div>")}n+="</div>";var _=scheduler._waiAria.gridAttrString();
n+="<div class='dhx_grid_area'><table "+_+">";for(var l=0;l<a.length;l++)n+=scheduler._grid._print_event_row(a[l],e);n+="</table></div>",scheduler._els.dhx_cal_data[0].innerHTML=n,scheduler._els.dhx_cal_data[0].lastChild.scrollTop=scheduler._grid._gridScrollTop||0;var h=scheduler._els.dhx_cal_data[0].getElementsByTagName("tr");scheduler._rendered=[];for(var l=0;l<h.length;l++)scheduler._rendered[l]=h[l]},scheduler._grid._getCellContent=function(e,t){var r,i=scheduler.getState().mode;return r=t.template?t.template(e.start_date,e.end_date,e):"date"==t.id?scheduler.templates[i+"_full_date"](e.start_date,e.end_date,e):"start_date"==t.id||"end_date"==t.id?scheduler.templates[i+"_single_date"](e[t.id]):scheduler.templates[i+"_field"](t.id,e);
},scheduler._grid._print_event_row=function(e,t){var r=[];e.color&&r.push("background:"+e.color),e.textColor&&r.push("color:"+e.textColor),e._text_style&&r.push(e._text_style),scheduler[t].rowHeight&&r.push("height:"+scheduler[t].rowHeight+"px");var i="";r.length&&(i="style='"+r.join(";")+"'");for(var a=scheduler[t].columns,s=scheduler.templates.event_class(e.start_date,e.end_date,e),n=scheduler._waiAria.gridRowAttrString(e),d="<tr "+n+" class='dhx_grid_event"+(s?" "+s:"")+"' event_id='"+e.id+"' "+i+">",l=(scheduler._grid._getViewName(t),
["text-align","vertical-align","padding-left","padding-right"]),o=0;o<a.length;o++){var _=scheduler._grid._getCellContent(e,a[o]),h=scheduler._waiAria.gridCellAttrString(e,a[o],_),c=scheduler._grid._getStyles(a[o],l),u=a[o].css?' class="'+a[o].css+'"':"";d+="<td "+h+" style='width:"+a[o].width+"px;"+c.join(";")+"' "+u+">"+_+"</td>"}return d+="<td class='dhx_grid_dummy'></td></tr>"},scheduler._grid._print_grid_header=function(e){for(var t="<div class='dhx_grid_line'>",r=scheduler[e].columns,i=[],a=r.length,s=scheduler._obj.clientWidth-2*r.length-20,n=0;n<r.length;n++){
var d=1*r[n].initialWidth;isNaN(d)||""===r[n].initialWidth||null===r[n].initialWidth||"boolean"==typeof r[n].initialWidth?i[n]=null:(a--,s-=d,i[n]=d)}for(var l=Math.floor(s/a),o=["text-align","padding-left","padding-right"],_=0;_<r.length;_++){var h=i[_]?i[_]:l;r[_].width=h-scheduler._grid._calcPadding(r[_],e);var c=scheduler._grid._getStyles(r[_],o);t+="<div style='width:"+(r[_].width-1)+"px;"+c.join(";")+"'>"+(void 0===r[_].label?r[_].id:r[_].label)+"</div>"}return t+="</div>"};
//# sourceMappingURL=../sources/ext/dhtmlxscheduler_grid_view.js.map